### ISSUE TITLE
How do you use ng-string in your application?

### ISSUE THREAD

**Issue by ghost** [goodeggs/ng-string#2]
So I've included the ng-string.js in my .html file, but when I tried to use the filter, I got this error:

`Error: [$injector:unpr] Unknown provider: stringCapitalizeFilterProvider <- stringCapitalize`

I tried to find out info on how to inject the dependency on this stackoverflow post:

http://stackoverflow.com/questions/15457720/angularjs-dependency-injection-in-services-factories-filters-etc
But I don't know that code I should add exactly.  Please add this to your documentation.

I tried, this, but it didn't work:

```
app.filter('string', ['$http', function(http){
    return function(data){
    }
}]);;
```

**Comment by ghost** [comment]
Wow, it was really simple:

var app = angular.module(<my-app-name>, ['string']);

Thanks for the nice filters!

**Comment by hazeledmands** [comment]
Oh, thanks for pointing this out! Glad you found it; we should totally update the documentation here.

**Comment by sebastientromp** [comment]
Indeed, had to look that up here too :)
